src/Entity/Intern.php
<?php

namespace App\Entity;

use App\Repository\InternRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: InternRepository::class)]
class Intern
{

    const INTERN_GETCARD_SUCCESSFULLY = 'INTERN_GETCARD_SUCCESSFULLY';
    const INTERN_INVALID_CARD = 'INTERN_INVALID_CARD'; 

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 30)]
    #[Assert\NotBlank()]
    #[Assert\Length(min: 2, max: 30)]
    #[Assert\Type('string')]
    private ?string $lastName = null;

    #[ORM\Column(length: 30)]
    #[Assert\NotBlank()]
    #[Assert\Length(min: 2, max: 30)]
    #[Assert\Type('string')]
    private ?string $firstName = null;

    #[ORM\Column(length: 45)]
    #[Assert\NotBlank()]
    #[Assert\Length(min: 2, max: 45)]
    #[Assert\Type('string')]
    private ?string $serialNumIntern = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\NotNull()]
    #[Assert\Date]
    private ?\DateTimeInterface $birthDate = null;

    #[ORM\Column(length: 50)]
    #[Assert\NotNull()]
    #[Assert\NotBlank()]
    #[Assert\Length(min: 2, max: 50)]
    #[Assert\Type('string')]
    private ?string $addressIntern = null;

    #[ORM\Column(length: 45)]
    #[Assert\NotNull()]
    #[Assert\NotBlank()]
    #[Assert\Length(min: 2, max: 45)]
    #[Assert\Type('string')]
    private ?string $city = null;

    #[ORM\Column]
    #[Assert\NotNull()]
    #[Assert\Positive()]
    #[Assert\Type('int')]
    private ?int $zipCode = null;

    #[ORM\Column(length: 1)]
    #[Assert\NotBlank()]
    #[Assert\NotNull()]
    #[Assert\Length(1)]
    #[Assert\Choice(['H', 'F', 'X'])]
    #[Assert\Type('string')]
    private ?string $sexIntern = null;

    #[ORM\Column(length: 25)]
    #[Assert\NotBlank()]
    #[Assert\Length(min: 10, max: 25)]
    #[Assert\Type('string')]
    private ?string $phoneNumberIntern = null;

    #[ORM\Column(length: 40)]
    #[Assert\NotBlank()]
    #[Assert\NotNull()]
    #[Assert\Email(
        message: 'L\'email {{ value }} n\'est pas valide.',
    )]
    private ?string $mailIntern = null;

    #[ORM\Column(length: 15, nullable: true)]
    #[Assert\Length(min: 2, max: 15)]
    #[Assert\Type('string')]
    private ?string $numberPlate = null;

    #[ORM\Column(length: 100)]
    #[Assert\NotBlank()]
    #[Assert\Length(min: 2, max: 100)]
    #[Assert\Type('string')]
    private ?string $formation = null;

    #[ORM\Column(length: 10)]
    #[Assert\NotBlank()]
    #[Assert\Length(min: 1, max: 10)]
    #[Assert\Type('string')]
    private ?string $formationAbbreviation = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\DateTime]
    #[Assert\NotBlank()]
    private ?\DateTimeInterface $arrivingIntern = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\DateTime]
    #[Assert\NotBlank()]
    private ?\DateTimeInterface $finishingIntern = null;

    #[ORM\Column]
    #[Assert\NotBlank()]
    #[Assert\Type('int')]
    private ?int $toNight = null;

    #[ORM\Column]
    #[Assert\NotBlank()]
    #[Assert\Type('int')]
    private ?int $remainingNight = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $imageProfil = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Room $Room = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Emergency $Emergency = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Wifi $Wifi = null;

    #[ORM\OneToMany(mappedBy: 'intern', targetEntity: Observation::class)]
    private Collection $Observations;

    #[ORM\OneToMany(mappedBy: 'intern', targetEntity: Subscribe::class, orphanRemoval: true)]
    private Collection $subscribes;


    public function __construct()
    {
        $this->Observations = new ArrayCollection();
        $this->subscribes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getSerialNumIntern(): ?string
    {
        return $this->serialNumIntern;
    }

    public function setSerialNumIntern(string $serialNumIntern): self
    {
        $this->serialNumIntern = $serialNumIntern;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birthDate;
    }

    public function setBirthDate(\DateTimeInterface $birthDate): self
    {
        $this->birthDate = $birthDate;

        return $this;
    }

    public function getAddressIntern(): ?string
    {
        return $this->addressIntern;
    }

    public function setAddressIntern(string $addressIntern): self
    {
        $this->addressIntern = $addressIntern;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getZipCode(): ?int
    {
        return $this->zipCode;
    }

    public function setZipCode(int $zipCode): self
    {
        $this->zipCode = $zipCode;

        return $this;
    }

    public function getSexIntern(): ?string
    {
        return $this->sexIntern;
    }

    public function setSexIntern(string $sexIntern): self
    {
        $this->sexIntern = $sexIntern;

        return $this;
    }

    public function getPhoneNumberIntern(): ?string
    {
        return $this->phoneNumberIntern;
    }

    public function setPhoneNumberIntern(string $phoneNumberIntern): self
    {
        $this->phoneNumberIntern = $phoneNumberIntern;

        return $this;
    }

    public function getMailIntern(): ?string
    {
        return $this->mailIntern;
    }

    public function setMailIntern(string $mailIntern): self
    {
        $this->mailIntern = $mailIntern;

        return $this;
    }

    public function getNumberPlate(): ?string
    {
        return $this->numberPlate;
    }

    public function setNumberPlate(?string $numberPlate): self
    {
        $this->numberPlate = $numberPlate;

        return $this;
    }

    public function getFormation(): ?string
    {
        return $this->formation;
    }

    public function setFormation(string $formation): self
    {
        $this->formation = $formation;

        return $this;
    }

    public function getFormationAbbreviation(): ?string
    {
        return $this->formationAbbreviation;
    }

    public function setFormationAbbreviation(string $formationAbbreviation): self
    {
        $this->formationAbbreviation = $formationAbbreviation;

        return $this;
    }

    public function getArrivingIntern(): ?\DateTimeInterface
    {
        return $this->arrivingIntern;
    }

    public function setArrivingIntern(\DateTimeInterface $arrivingIntern): self
    {
        $this->arrivingIntern = $arrivingIntern;

        return $this;
    }

    public function getFinishingIntern(): ?\DateTimeInterface
    {
        return $this->finishingIntern;
    }

    public function setFinishingIntern(\DateTimeInterface $finishingIntern): self
    {
        $this->finishingIntern = $finishingIntern;

        return $this;
    }

    public function getToNight(): ?int
    {
        return $this->toNight;
    }

    public function setToNight(int $toNight): self
    {
        $this->toNight = $toNight;

        return $this;
    }

    public function getRemainingNight(): ?int
    {
        return $this->remainingNight;
    }

    public function setRemainingNight(int $remainingNight): self
    {
        $this->remainingNight = $remainingNight;

        return $this;
    }

    public function getImageProfil(): ?string
    {
        return $this->imageProfil;
    }

    public function setImageProfil(?string $imageProfil): self
    {
        $this->imageProfil = $imageProfil;

        return $this;
    }

    public function getRoom(): ?Room
    {
        return $this->Room;
    }

    public function setRoom(Room $Room): self
    {
        $this->Room = $Room;

        return $this;
    }

    public function getEmergency(): ?Emergency
    {
        return $this->Emergency;
    }

    public function setEmergency(Emergency $Emergency): self
    {
        $this->Emergency = $Emergency;

        return $this;
    }

    public function getWifi(): ?Wifi
    {
        return $this->Wifi;
    }

    public function setWifi(Wifi $Wifi): self
    {
        $this->Wifi = $Wifi;

        return $this;
    }

    /**
     * @return Collection<int, Observation>
     */
    public function getObservations(): Collection
    {
        return $this->Observations;
    }

    public function addObservation(Observation $observation): self
    {
        if (!$this->Observations->contains($observation)) {
            $this->Observations->add($observation);
            $observation->setIntern($this);
        }

        return $this;
    }

    public function removeObservation(Observation $observation): self
    {
        if ($this->Observations->removeElement($observation)) {
            // set the owning side to null (unless already changed)
            if ($observation->getIntern() === $this) {
                $observation->setIntern(null);
            }
        }

        return $this;
    }

    /**

templates/partials/_footer.html.twig
<div class="container-fluid px-0 mt-auto fixed-bottom">
    <footer class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between ">
        <div class="d-flex flex-wrap align-items-center" id="navbarNav">
            <a class="navbar-brand" href="/"><img src={{asset('media/img/logo_white.png')}} width="96" height="16"
                    alt="logo Glitch" class="ms-2"></a>
            <ul class="nav ">
                <li class="nav-item active">
                    <img class="icon m-2 " width="40px" height="40px" src={{asset('media/img/afpar_logo.png')}} alt='AFPAR Logo' />
                </li>
                <li class="nav-item active">
                    <img class="icon m-2 " width="40px" height="40px" src={{asset('media/img/Logo_Meteo_France.png')}} alt='Meteo France Logo' />
                </li>
                <li class="nav-item active">
                    <img class="icon m-2 " width="40px" height="40px" src={{asset('media/img/SFR_logo_2014.png')}} alt='SFR logo' />
                </li>
            </ul>
        </div>
    
        <div class="d-flex " id="navbarNav">
            <ul class="navbar-nav mx-3">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Mentions Légales</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contacts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Plan d'accès</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Règlement intérieur</a>
                </li>
            </ul>
        </div>
    </footer>
</div>

templates/partials/_header.html.twig
<div class="container-fluid px-0">

    {# header avec condition d'affichage #}
    <header class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between ">
        <div class="d-flex mb-2 mb-lg-0 align-items-center">
            <a href="/"><img src={{asset('media/img/afpar_logo.png')}} width="64" height="64" alt="" class="ms-2"></a>
            <a class="navbar-brand" href="/"><img src={{asset('media/img/logo_white.png')}} width="192" height="33"
                    alt="logo Glitch" class="ms-2"></a>
        </div>
        {% include "pages/sercurity/login.html.twig" %}
    </header>

    {# Bar de navigation avec condition d'affichage #}
    {% include "partials/_navbar.html.twig" %}
</div>

templates/partials/_modal.html.twig
<!-- Modal -->
<div class="modal modalCard fade" id="{{idModal}}" tabindex="-1" role="dialog" aria-labelledby="{{idModal}}" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="{{idModalTitle}}">{{ModalTitle}}</h5>
                <button type="button" class="{{classButton}}" data-bs-dismiss="modal" aria-label="{{ariaLabel}}">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body p-0 p-sm-2" id="{{idModalBody}}">
                {# ici le code importer par la réponse de la requête ajax du code javaScript #}
            </div>
        </div>
    </div>
</div>

<div class="attribute" data-idModal="{{idModal}}" data-idModalBody="{{idModalBody}}" data-requestUrl="{{requestUrl}}"></div>

templates/partials/_navbar.html.twig
    {# Bar de navigation avec condition d'affichage #}
    {% if is_granted('ROLE_ADMIN') %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-secondary py-2">
            <ul class="navbar-nav ms-3">
                <li class="nav-item active">
                    <a class="nav-link ps-0" href="{{ path('management.index') }}"><i class="fa-solid fa-house me-2"></i>Accueil</a>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link" href="#hookActivity"><i class="fa-solid fa-person-biking me-2"></i>Activité</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('statistic.index') }}"><i class="fa-solid fa-chart-line me-2"></i>Statistique</a>
                </li>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown"
                    aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fa-solid fa-plus-minus me-1"></i>
                                Gestion
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                                <li><a class="dropdown-item" href="{{ path('management.room') }}"><i class="fa-solid fa-bed me-2"></i>Chambres</a></li>
                                <li><a class="dropdown-item" href="{{ path('management.observation') }}"><i class="fa-solid fa-paper-plane me-2"></i>Signalement</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </ul>
        </nav>
    {% elseif is_granted('ROLE_USER') %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-secondary py-2">
            <ul class="navbar-nav ms-3">
                <li class="nav-item active">
                    <a class="nav-link ps-0"><i class="fa-solid fa-house me-2"></i>Accueil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="fa-solid fa-paper-plane me-2"></i>Signalement</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="fa-solid fa-person-biking me-2"></i>Activité</a>
                </li>
            </ul>
        </nav>
    {% else %}
    
    {% endif %}
</div>